"""
pathoai/tumor_bulk/exporters.py
==============================
Tumor Bulk GeoJSON Exporter.

Exports extracted ROIs and polygon boundaries to standard GeoJSON formats
compatible with digital pathology software (e.g. QuPath).

Author: PathoAI Research Team
Created: 2026-07-19
Milestone: 6.5
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List


def export_rois_to_geojson(rois: List[Dict[str, Any]], output_path: str | Path) -> None:
    """Exports a list of ROI dictionaries to a standardized GeoJSON file.

    Parameters
    ----------
    rois : List[Dict[str, Any]]
        List of ROI dictionaries generated by generate_rois.
    output_path : str | Path
        Path to the output file.
    """
    features = []

    for roi in rois:
        contours = roi.get("contours", [])
        if not contours:
            continue

        # In GeoJSON Polygon coordinates format:
        # [[[x1, y1], [x2, y2], ..., [x1, y1]], [hole1_coords], ...]
        # Ensure each ring is closed (first coordinate equals last)
        coordinates = []
        for c in contours:
            if len(c) < 3:
                continue
            ring = list(c)
            if ring[0] != ring[-1]:
                ring.append(ring[0])
            coordinates.append(ring)

        if not coordinates:
            continue

        feature = {
            "type": "Feature",
            "properties": {
                "roi_id": int(roi["roi_id"]),
                "area_um2": float(roi["area_um2"]),
                "perimeter_um": float(roi["perimeter_um"]),
                "bbox_yxyx": list(roi["bbox_yxyx"]),
                "centroid_xy": list(roi["centroid_xy"]),
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": coordinates,
            },
        }
        features.append(feature)

    geojson_data = {
        "type": "FeatureCollection",
        "features": features,
    }

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(geojson_data, f, indent=2, ensure_ascii=False)
