"""
pathoai/tumor_bulk/exporters.py
==============================
Tumor Bulk GeoJSON Exporter.

Exports extracted TumorROI structures and polygon boundaries to standard GeoJSON
FeatureCollection annotations.

Author: PathoAI Research Team
Created: 2026-07-19
Milestone: 6.5
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

from pathoai.core.types import TumorROI


def export_rois_to_geojson(rois: List[TumorROI], output_path: str | Path) -> None:
    """Exports a list of TumorROI objects to a standardized GeoJSON file.

    Parameters
    ----------
    rois : List[TumorROI]
        List of TumorROI objects generated by generate_rois.
    output_path : str | Path
        Path to the output file.
    """
    features = []

    for roi in rois:
        if not roi.contours:
            continue

        # In GeoJSON Polygon coordinates format:
        # [[[x1, y1], [x2, y2], ..., [x1, y1]], [hole1_coords], ...]
        coordinates = []
        for poly in roi.contours:
            if len(poly.exterior) < 3:
                continue
            ring = [p.to_tuple() for p in poly.exterior]
            # Ensure the ring is closed
            if ring[0] != ring[-1]:
                ring.append(ring[0])
            coordinates.append(ring)

        if not coordinates:
            continue

        feature = {
            "type": "Feature",
            "properties": {
                "roi_id": int(roi.roi_id),
                "class_label": str(roi.class_label),
                "area_px": int(roi.area_px),
                "area_um2": float(roi.area_um2),
                "perimeter_um": float(roi.perimeter_um),
                "eccentricity": float(roi.eccentricity),
                "solidity": float(roi.solidity),
                "compactness": float(roi.compactness),
                "equivalent_diameter_um": float(roi.equivalent_diameter_um),
                "bbox_yxyx": list(roi.bbox.to_yxyx()),
                "centroid_xy": list(roi.centroid.to_tuple()),
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": coordinates,
            },
        }
        features.append(feature)

    geojson_data = {
        "type": "FeatureCollection",
        "features": features,
    }

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(geojson_data, f, indent=2, ensure_ascii=False)
